# docker compose -f docker-compose.prod.yml up -d --build
services:
  app:
    build:
      context: .
      target: prod
    image: nebus-test:prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
